appVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  namespace: my-namespace
  labels: 
    app: frontend-app
spec:
  replicaCount: 2
  selector:
   matchLabels:
    app: frontend
  template:
    spec:
      labels:
        app: frontend
      spec:
        containers:
          - name: frontend_app
            image: chandrumm/pharnaapp:15
            imagePullPolicy: IfNotPresent
            ports:
              containerPort: 5000
